app/models.py
from . import db


class Restaurant(db.Model):

    __tablename__ = 'restaurant'

    name = db.Column(db.String(80), nullable=False)
    id = db.Column(db.Integer, primary_key=True)


class MenuItem(db.Model):

    __tablename__ = 'menu_item'

    name = db.Column(db.String(80), nullable=False)
    id = db.Column(db.Integer, primary_key=True)
    course = db.Column(db.String(250))
    description = db.Column(db.String(250))
    price = db.Column(db.String(8))
    restaurant_id = db.Column(db.Integer, db.ForeignKey('restaurant.id'))
    restaurant = db.relationship(Restaurant)

app/menu_items/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class CreateMenuItem(FlaskForm):
    name = StringField('Name:', validators=[DataRequired()])
    description = TextAreaField('Description:')
    course = TextAreaField('Course:')
    price = StringField('Price: ', validators=[DataRequired()])
    submit = SubmitField('Create!')

app/restaurants/forms.py
from flask_wtf import FlaskForm
from wtforms import HiddenField, StringField, SubmitField
from wtforms.validators import DataRequired


class CreateRestaurant(FlaskForm):
    name = StringField('Name:', validators=[DataRequired()])
    submit = SubmitField('Create!')


class EditRestaurant(FlaskForm):
    id = HiddenField()
    name = StringField('Name:', validators=[DataRequired()])
    submit = SubmitField('Edit!')


class DeleteRestaurant(FlaskForm):
    submit = SubmitField('Delete')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from config import config

bootstrap = Bootstrap()
db = SQLAlchemy()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    config[config_name].init_app(app)
    bootstrap.init_app(app)
    db.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .restaurants import restaurants as restaurants_blueprint
    app.register_blueprint(restaurants_blueprint, url_prefix='/restaurants')

    from .menu_items import menu_items as menu_items_blueprint
    app.register_blueprint(menu_items_blueprint, url_prefix='/<int:restaurant_id>/menu')

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from . import main


@main.route('/')
def show_restaurants():
    return 'Hello World'

app/menu_items/__init__.py
from flask import Blueprint

menu_items = Blueprint('menu_items', __name__)

from . import views

app/menu_items/views.py
from flask import render_template, request, flash, redirect, url_for
from .. import db
from .forms import CreateMenuItem
from ..models import MenuItem
from . import menu_items as app_menu_items


@app_menu_items.route('/')
def show_menu(restaurant_id):
    menu_items = db.session.query(MenuItem).filter_by(restaurant_id=restaurant_id).all()
    return render_template('menus.html', menu_items=menu_items, restaurant_id=restaurant_id)


@app_menu_items.route('/new', methods=['GET', 'POST'])
def create_menu(restaurant_id):
    if request.method == 'GET':
        return render_template('create_menu_item.html', form=CreateMenuItem(), restaurant_id=restaurant_id)

    if request.method == 'POST':
        form = CreateMenuItem()
        if form.validate_on_submit():
            menu_item = MenuItem()
            menu_item.name = form.name.data
            menu_item.description = form.description.data
            menu_item.course = form.course.data
            menu_item.price = form.price.data
            menu_item.restaurant_id = restaurant_id
            db.session.add(menu_item)
            db.session.commit()
            flash('New Menu item created!')
        else:
            flash('Unspected error on create menu item!')

        return redirect(url_for('.show_menu', restaurant_id=restaurant_id))

app/restaurants/__init__.py
from flask import Blueprint

restaurants = Blueprint('restaurants', __name__)

from . import views

app/restaurants/views.py
from flask import render_template, request, flash, redirect, url_for
from . import restaurants as app_restaurants
from .forms import CreateRestaurant, EditRestaurant, DeleteRestaurant
from .. import db
from ..models import Restaurant


@app_restaurants.route('/')
def show_restaurants():
    restaurants = db.session.query(Restaurant).all()
    return render_template('restaurants.html', restaurants=restaurants)


@app_restaurants.route('/new', methods=['GET','POST'])
def create_restaurant():
    if request.method == 'GET':
        return render_template('create_restaurant.html', form=CreateRestaurant())
    if request.method == 'POST':
        form = CreateRestaurant()
        if form.validate_on_submit():
            restaurant = Restaurant()
            restaurant.name = form.name.data
            db.session.add(restaurant)
            db.session.commit()
            flash('New restaraunt created!')
            return redirect(url_for('.show_restaurants'))

        return 'aconteceu algo de errado'


@app_restaurants.route('/<int:restaurant_id>/edit', methods=['GET','POSt'])
def edit_restaurant(restaurant_id):

    if request.method == 'GET':
        restaurant = db.session.query(Restaurant).filter_by(id=restaurant_id).first()
        if restaurant is not None:
            form = EditRestaurant()
            form.name.data = restaurant.name
            form.id.data = restaurant.id
            return render_template('edit_restaurant.html', form=form)
        else:
            flash('Pay attention, unspected error on edit restaurant ' + restaurant_id)
            return redirect(url_for('.show_restaurants'))

    if request.method == 'POST':
        form = EditRestaurant()
        restaurant = db.session.query(Restaurant).filter_by(id=restaurant_id).one()
        if restaurant is not None and form.validate_on_submit():
            restaurant.name = form.name.data
            db.session.add(restaurant)
            db.session.commit()
            flash('Restaurant edited!')
            return redirect(url_for('.show_restaurants'))


@app_restaurants.route('/<int:restaurant_id>/delete', methods=['GET', 'POST'])
def delete_restaurant(restaurant_id):

    if request.method == 'GET':
        restaurant = db.session.query(Restaurant).filter_by(id=restaurant_id).first()
        if restaurant is not None:
            form = DeleteRestaurant()
            return render_template('delete_restaurant.html', form=form, restaurant=restaurant)
        else:
            flash('Pay attention, uspected error on delete restaurant')
            return redirect(url_for('.show_restaurants'))

    if request.method == 'POST':
        restaurant = db.session.query(Restaurant).filter_by(id=restaurant_id).one()
        if restaurant is not None:
            db.session.delete(restaurant)
            db.session.commit()
            flash('Restaurant deleted!')
        else:
            flash('Pay attention, uspected error on delete restaurant')

        return redirect(url_for('.show_restaurants'))

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% block title %} Restaurant Menu!!! {% endblock %}
{% block navbar %}
{% endblock %}
{% block content %}
<div class="container">
  {% block page_content %}{% endblock %}
</div>
{% endblock %}

app/templates/create_menu_item.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
  <div style="padding:16px 0">
    <div class="btn-group">
      <a class="btn btn-default btn-sm" href="{{ url_for('.show_menu', restaurant_id=restaurant_id) }}">Cancel</a>
    </div>
  </div>
  {{ wtf.quick_form(form) }}
{% endblock %}

app/templates/create_restaurant.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
  <div style="padding:16px 0">
    <div class="btn-group">
      <a class="btn btn-default btn-sm" href="{{ url_for('.show_restaurants') }}">Cancel</a>
    </div>
  </div>
  {{ wtf.quick_form(form) }}
{% endblock %}

app/templates/delete_restaurant.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
  <div style="padding:16px 0">
    <div class="btn-group">
      <a class="btn btn-default btn-sm" href="{{ url_for('.show_restaurants') }}">Cancel</a>
    </div>
  </div>
  <div class="jumbotron">
    <p>Do you want delete "{{ restaurant.name }}"</p>
    {{ wtf.quick_form(form) }}
  </div>
{% endblock %}

app/templates/edit_restaurant.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
  <div style="padding:16px 0">
    <div class="btn-group">
      <a class="btn btn-default btn-sm" href="{{ url_for('.show_restaurants') }}">Cancel</a>
    </div>
  </div>
  {{ wtf.quick_form(form) }}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block page_content %}
  <div class="page-header">
    <h1>Hello World!</h1>
  </div>
{% endblock %}

app/templates/menus.html
{% extends 'base.html' %}
{% block page_content %}
  {% for messages in get_flashed_messages() %}
      <div class="alert alert-sm alert-info">{{ messages }}</div>
  {% endfor %}
  <div style="padding:16px 0">
    <div class="btn-group">
      <a class="btn btn-default btn-sm" href="{{url_for('restaurants.show_restaurants')}}">Back</a>
      <a class="btn btn-default btn-sm" href="{{url_for('.create_menu', restaurant_id=restaurant_id)}}">New</a>
    </div>
  </div>
  <ul class="list-group">
    {%for item in menu_items %}	  
    <li class="list-group-item">
      <h4 class="list-group-item-heading">
        {{item.name}}
      </h4>
      <p class="list-group-item-text">  
        <a class="btn btn-default btn-sm" href="#">Edit</a>
	<a class="btn btn-default btn-sm" href="#">Delete</a>
      </p> 
    </li>
    {% endfor %}
  </ul>
{% endblock %}

app/templates/restaurants.html
{% extends 'base.html' %}
{% block page_content %}
  {% for messages in get_flashed_messages() %}
      <div class="alert alert-sm alert-info">{{ messages }}</div>
  {% endfor %}
  <div style="padding:16px 0">
    <div class="btn-group">
      <a class="btn btn-default btn-sm" href="{{ url_for('.create_restaurant') }}">New</a>
    </div>
  </div>
  <ul class="list-group">
    {%for restaurant in restaurants %}	  
    <li class="list-group-item">
      <h4 class="list-group-item-heading">
        {{restaurant.name}}
	<!--<span class="badge">0</span>-->
      </h4>
      <p class="list-group-item-text">
      <a class="btn btn-default btn-sm" href="{{ url_for('menu_items.show_menu',restaurant_id=restaurant.id) }}">Menu items</a>
        <a class="btn btn-default btn-sm" href="{{ url_for('.edit_restaurant', restaurant_id=restaurant.id) }}">Edit</a>
	    <a class="btn btn-default btn-sm" href="{{ url_for('.delete_restaurant', restaurant_id=restaurant.id) }}">Delete</a>
      </p> 
    </li>
    {% endfor %}
  </ul>
{% endblock %}